apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: argo-worflow-test-
  labels:
    workflows.argoproj.io/archive-strategy: "false"
  annotations:
    workflows.argoproj.io/description: |
      This is a simple hello world example.
spec:
  entrypoint: whalesay
  templates:
    - name: whalesay
      container:
        image: argo-workflow:latest
        imagePullPolicy: Never
        command: ["node", "run"]
        args: ["hello world"]